plugins {
    id 'multiloader-loader'
}

if (!project.fabric_version) {
    tasks.configureEach {
        enabled = false
    }
    return
}

apply plugin: minecraft_unobfuscated.toBoolean() ? 'net.fabricmc.fabric-loom' : 'net.fabricmc.fabric-loom-remap'

base {
    archivesName = "${mod_file_name}-fabric-${minecraft_version_label}"
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "shedaniel"
        url = 'https://maven.shedaniel.me'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    if (!minecraft_unobfuscated.toBoolean()) {
        mappings loom.layered {
            officialMojangMappings()
            if (parchment_minecraft && parchment_version) {
                parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
            }
        }
    }

    def fabricDependencyConfiguration = minecraft_unobfuscated.toBoolean() ? 'implementation' : 'modImplementation'
    add(fabricDependencyConfiguration, "net.fabricmc:fabric-loader:${fabric_loader_version}")
    add(fabricDependencyConfiguration, "net.fabricmc.fabric-api:fabric-api:${fabric_version}")

    if (project.cloth_config_version) {
        // Cloth Config
        add(fabricDependencyConfiguration, "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
            exclude(group: "net.fabricmc.fabric-api")
        }
    }

    if (project.modmenu_version) {
        add(fabricDependencyConfiguration, "com.terraformersmc:modmenu:${project.modmenu_version}")
    }
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
    }
}
