minecraft_unobfuscated=false
java_version=21
minecraft_version=1.21.9
minecraft_version_label=1.21.9
minecraft_version_range=[1.21.9, 1.21.9]
fabric_minecraft_version_range=>=1.21 <26.1
neo_form_version=1.21.9-20250930.151910
parchment_minecraft=
parchment_version=
fabric_version=0.134.1+1.21.9
fabric_loader_version=0.19.2
modmenu_version=
cloth_config_version=
forge_version=59.0.5
forge_loader_version_range=[59,)
forge_dependency_version_range=[59.0.0,)
forge_minecraft_version_range=[1.21.9, 1.21.9]
neoforge_version=21.9.16-beta
neoforge_loader_version_range=[4,)
neoforge_dependency_version_range=[21.9.0-beta,)
neoforge_minecraft_version_range=[1.21.9, 1.21.9]
