minecraft_unobfuscated=true
java_version=25
minecraft_version=26.1.1
minecraft_version_label=26.1.1
minecraft_version_range=[26.1.1, 26.1.1]
fabric_minecraft_version_range=
neo_form_version=26.1.1-1
parchment_minecraft=
parchment_version=
fabric_version=
fabric_loader_version=
modmenu_version=
cloth_config_version=
forge_version=63.0.2
forge_loader_version_range=[63,)
forge_dependency_version_range=[63.0.2,)
forge_minecraft_version_range=[26.1.1, 26.1.1]
neoforge_version=26.1.1.15-beta
neoforge_loader_version_range=[5,)
neoforge_dependency_version_range=[26.1.1.0-beta,)
neoforge_minecraft_version_range=[26.1.1, 26.1.1]
